server:
  port: 8080
  servlet:
    context-path: /identity

#spring:
#  datasource:
#    url: ${DBMS_CONNECTION:jdbc:mysql://localhost:3306/identity_service}
#    driverClassName: "com.mysql.cj.jdbc.Driver"
#    password: ${DBMS_PASSWORD:root}
#    username: ${DBMS_USERNAME:root}
#  jpa:
#    hibernate:
#      ddl-auto: update
#    show-sql: true

spring:

  servlet:
    multipart:
      enabled: true
      max-file-size: 5MB
      max-request-size: 20MB

  datasource:
    url: jdbc:postgresql://localhost:5432/JwtWebToken
    username: postgres
    password: 12345678
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
   # database-platform: org.hibernate.dialect.PostgreSQLDialect
      ddl-auto: update
    show-sql: true


jwt:
  signerKey: "1TjXchw5FloESb63Kc+DFhTARvpWL4jUGCwfGWxuG5SIf/1y/LgJxHnMqaF6A/ij"
  valid-duration: 3600 # in second
  refreshable-duration: 36000 # in seconds


cloudinary:
  cloud_name: dk21j368x
  api_key: 972728917961882
  api_secret: j0rFcCHR4M009AGT3OfbDL1_df4
